server:
  port: ${ENV_PORT:8000}
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:h2:mem:ecommerce;DATABASE_TO_LOWER=true;CASE_INSENSITIVE_IDENTIFIERS=true;
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-ui
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: true

filer:
  method:
    apply: QUERY # options: SPECIFICATION or QUERY

flyway:
  user: sa
  password:
  url: jdbc:h2:mem:ecommerce;DATABASE_TO_LOWER=true;CASE_INSENSITIVE_IDENTIFIERS=true;
  locations: classpath:db/migration

openapi:
  servers:
    - url: http://localhost:${ENV_PORT:8000}/api/v1
      description: Production server
  info:
    title: ECOMMERCE API
    contact:
      name: Support Team
      email: hello@between.com
    description: API for ecommerce services
  language: i18n/swagger_messages.properties # use para ES: "i18n/swagger_messages_es" and for EN: swagger_messages

spring-doc:
  api-docs:
    enabled: true
    path: /api-docs
    resolve-schema-properties: true
  swagger-ui:
    path: /swagger-ui.html
    displayRequestDuration: true
    tagsSorter: alpha
    resolve-schema-properties: true
